package tech.hellsoft.trading.integration;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import tech.hellsoft.trading.dto.server.LoginOKMessage;
import tech.hellsoft.trading.dto.server.TeamRole;
import tech.hellsoft.trading.internal.serialization.JsonSerializer;

/**
 * Integration test to verify Java client can correctly parse JSON from Go server.
 *
 * <p>This test uses ACTUAL JSON output from the Go server's TestLoginOKMessageJSONSerialization
 * test to ensure end-to-end compatibility.
 */
class GoServerJsonCompatibilityTest {

  /**
   * This is the ACTUAL JSON generated by the Go server in TestLoginOKMessageJSONSerialization. It
   * was copied directly from the test output.
   *
   * <p>Key verification: The JSON contains "baseEnergy":3,"levelEnergy":2 in camelCase format.
   */
  private static final String GO_SERVER_LOGIN_OK_JSON =
      "{"
          + "\"type\":\"LOGIN_OK\","
          + "\"team\":\"TestTeam\","
          + "\"species\":\"Premium\","
          + "\"initialBalance\":100000,"
          + "\"currentBalance\":100000,"
          + "\"inventory\":{\"FOSFO\":10},"
          + "\"authorizedProducts\":[\"FOSFO\",\"PITA\"],"
          + "\"recipes\":{\"FOSFO\":{\"type\":\"BASIC\",\"ingredients\":{},\"premiumBonus\":1}},"
          + "\"role\":{"
          + "\"branches\":2,"
          + "\"maxDepth\":4,"
          + "\"decay\":0.75,"
          + "\"budget\":25,"
          + "\"baseEnergy\":3,"
          + "\"levelEnergy\":2"
          + "},"
          + "\"serverTime\":\"2025-11-24T07:57:44-05:00\""
          + "}";

  @Test
  @DisplayName("Should parse actual Go server LOGIN_OK JSON with energy fields")
  void testGoServerJsonParsing() {
    // Parse the exact JSON from Go server
    LoginOKMessage message = JsonSerializer.fromJson(GO_SERVER_LOGIN_OK_JSON, LoginOKMessage.class);

    // Verify basic fields
    assertNotNull(message, "Message should not be null");
    assertEquals("TestTeam", message.getTeam(), "Team name should match");
    assertEquals("Premium", message.getSpecies(), "Species should match");
    assertEquals(100000.0, message.getInitialBalance(), 0.01, "Initial balance should match");
    assertEquals(100000.0, message.getCurrentBalance(), 0.01, "Current balance should match");

    // Verify role exists
    TeamRole role = message.getRole();
    assertNotNull(role, "Role should not be null");

    // CRITICAL: Verify energy fields are correctly parsed
    assertNotNull(role.getBaseEnergy(), "baseEnergy should NOT be null");
    assertNotNull(role.getLevelEnergy(), "levelEnergy should NOT be null");

    assertEquals(3.0, role.getBaseEnergy(), 0.001, "baseEnergy should be 3.0");
    assertEquals(2.0, role.getLevelEnergy(), 0.001, "levelEnergy should be 2.0");

    // Verify other role fields
    assertEquals(2, role.getBranches(), "branches should be 2");
    assertEquals(4, role.getMaxDepth(), "maxDepth should be 4");
    assertEquals(0.75, role.getDecay(), 0.001, "decay should be 0.75");
    assertEquals(25.0, role.getBudget(), 0.001, "budget should be 25.0");

    System.out.println("✅ SUCCESS: Java client correctly parsed Go server JSON!");
    System.out.println("   baseEnergy: " + role.getBaseEnergy());
    System.out.println("   levelEnergy: " + role.getLevelEnergy());
  }

  @Test
  @DisplayName("Should handle Go server JSON with default energy values")
  void testGoServerJsonWithDefaultEnergy() {
    // This simulates JSON from Go server AFTER applying default values
    // (when database had zero energy values)
    String jsonWithDefaults =
        "{"
            + "\"type\":\"LOGIN_OK\","
            + "\"team\":\"TestTeam\","
            + "\"species\":\"Premium\","
            + "\"initialBalance\":100000,"
            + "\"currentBalance\":100000,"
            + "\"inventory\":{},"
            + "\"authorizedProducts\":[\"FOSFO\"],"
            + "\"recipes\":{},"
            + "\"role\":{"
            + "\"branches\":2,"
            + "\"maxDepth\":4,"
            + "\"decay\":0.75,"
            + "\"budget\":25,"
            + "\"baseEnergy\":3,"
            + "\"levelEnergy\":2"
            + "},"
            + "\"serverTime\":\"2025-11-24T07:57:44-05:00\""
            + "}";

    LoginOKMessage message = JsonSerializer.fromJson(jsonWithDefaults, LoginOKMessage.class);

    assertNotNull(message, "Message should not be null");
    TeamRole role = message.getRole();
    assertNotNull(role, "Role should not be null");

    // Verify default values were applied by Go server and parsed correctly
    assertEquals(3.0, role.getBaseEnergy(), 0.001, "Default baseEnergy should be 3.0");
    assertEquals(2.0, role.getLevelEnergy(), 0.001, "Default levelEnergy should be 2.0");

    System.out.println("✅ SUCCESS: Default energy values correctly parsed!");
  }

  @Test
  @DisplayName("Should verify JSON contains camelCase field names, not snake_case")
  void testGoServerUsesCamelCase() {
    // Verify the Go server JSON uses camelCase
    assertTrue(
        GO_SERVER_LOGIN_OK_JSON.contains("\"baseEnergy\""),
        "JSON should contain camelCase 'baseEnergy'");
    assertTrue(
        GO_SERVER_LOGIN_OK_JSON.contains("\"levelEnergy\""),
        "JSON should contain camelCase 'levelEnergy'");
    assertTrue(
        GO_SERVER_LOGIN_OK_JSON.contains("\"maxDepth\""),
        "JSON should contain camelCase 'maxDepth'");

    // Verify it does NOT use snake_case
    assertFalse(
        GO_SERVER_LOGIN_OK_JSON.contains("\"base_energy\""),
        "JSON should NOT contain snake_case 'base_energy'");
    assertFalse(
        GO_SERVER_LOGIN_OK_JSON.contains("\"level_energy\""),
        "JSON should NOT contain snake_case 'level_energy'");
    assertFalse(
        GO_SERVER_LOGIN_OK_JSON.contains("\"max_depth\""),
        "JSON should NOT contain snake_case 'max_depth'");

    System.out.println("✅ SUCCESS: Go server uses camelCase as expected!");
  }

  @Test
  @DisplayName("Regression test: Verify old LOWER_CASE_WITH_UNDERSCORES would fail")
  void testOldConfigurationWouldFail() {
    // This test documents what WOULD happen with the old Gson configuration
    // (LOWER_CASE_WITH_UNDERSCORES naming policy)

    // If we had the old config, it would look for "base_energy" and "level_energy"
    // but the Go server sends "baseEnergy" and "levelEnergy", so they would be null

    // With the NEW config (IDENTITY naming policy), this works correctly
    LoginOKMessage message = JsonSerializer.fromJson(GO_SERVER_LOGIN_OK_JSON, LoginOKMessage.class);
    TeamRole role = message.getRole();

    // These assertions would FAIL with the old configuration
    // but PASS with the new configuration
    assertNotNull(role.getBaseEnergy(), "With IDENTITY policy, baseEnergy should NOT be null");
    assertNotNull(role.getLevelEnergy(), "With IDENTITY policy, levelEnergy should NOT be null");

    System.out.println(
        "✅ SUCCESS: New IDENTITY naming policy correctly handles camelCase from Go!");
  }

  @Test
  @DisplayName("End-to-end verification: MongoDB -> Go -> JSON -> Java")
  void testFullStackCompatibility() {
    // This test represents the full flow:
    // 1. MongoDB stores data with fields: baseEnergy, levelEnergy
    // 2. Go server reads from MongoDB
    // 3. Go server marshals to JSON with camelCase: {"baseEnergy":3,"levelEnergy":2}
    // 4. Java client receives and parses the JSON

    // Using actual Go server JSON
    LoginOKMessage message = JsonSerializer.fromJson(GO_SERVER_LOGIN_OK_JSON, LoginOKMessage.class);

    // Verify the complete flow works
    assertNotNull(message, "Full flow: Message should be parsed");
    assertNotNull(message.getRole(), "Full flow: Role should exist");
    assertNotNull(message.getRole().getBaseEnergy(), "Full flow: baseEnergy should exist");
    assertNotNull(message.getRole().getLevelEnergy(), "Full flow: levelEnergy should exist");

    // Verify exact values from MongoDB
    assertEquals(
        3.0, message.getRole().getBaseEnergy(), 0.001, "Full flow: baseEnergy value correct");
    assertEquals(
        2.0, message.getRole().getLevelEnergy(), 0.001, "Full flow: levelEnergy value correct");

    System.out.println("✅ SUCCESS: Full stack MongoDB -> Go -> Java works correctly!");
    System.out.println("   Flow verified: Database → Server → JSON → Client");
    System.out.println("   baseEnergy: " + message.getRole().getBaseEnergy());
    System.out.println("   levelEnergy: " + message.getRole().getLevelEnergy());
  }
}
